/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/comments/': RouteRecordInfo<'/comments/', '/comments', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/群论笔记-第一章-群的基本知识': RouteRecordInfo<'/posts/群论笔记-第一章-群的基本知识', '/posts/群论笔记-第一章-群的基本知识', Record<never, never>, Record<never, never>>,
    '/posts/群论笔记-绪论': RouteRecordInfo<'/posts/群论笔记-绪论', '/posts/群论笔记-绪论', Record<never, never>, Record<never, never>>,
    '/posts/习思想复习-导论-马克思主义中国化时代化新的飞跃': RouteRecordInfo<'/posts/习思想复习-导论-马克思主义中国化时代化新的飞跃', '/posts/习思想复习-导论-马克思主义中国化时代化新的飞跃', Record<never, never>, Record<never, never>>,
    '/posts/习思想复习-第一章-新时代坚持和发展中国特色社会主义': RouteRecordInfo<'/posts/习思想复习-第一章-新时代坚持和发展中国特色社会主义', '/posts/习思想复习-第一章-新时代坚持和发展中国特色社会主义', Record<never, never>, Record<never, never>>,
    '/posts/习思想资料整理-第十章-建设社会主义文化强国': RouteRecordInfo<'/posts/习思想资料整理-第十章-建设社会主义文化强国', '/posts/习思想资料整理-第十章-建设社会主义文化强国', Record<never, never>, Record<never, never>>,
    '/posts/Docker': RouteRecordInfo<'/posts/Docker', '/posts/Docker', Record<never, never>, Record<never, never>>,
    '/posts/Gauss-Bonnet-Theorem': RouteRecordInfo<'/posts/Gauss-Bonnet-Theorem', '/posts/Gauss-Bonnet-Theorem', Record<never, never>, Record<never, never>>,
    '/posts/Group-theory-chapter-2': RouteRecordInfo<'/posts/Group-theory-chapter-2', '/posts/Group-theory-chapter-2', Record<never, never>, Record<never, never>>,
    '/posts/Group-theory-chapter-3': RouteRecordInfo<'/posts/Group-theory-chapter-3', '/posts/Group-theory-chapter-3', Record<never, never>, Record<never, never>>,
    '/posts/Group-theory-chapter-4': RouteRecordInfo<'/posts/Group-theory-chapter-4', '/posts/Group-theory-chapter-4', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/Linux': RouteRecordInfo<'/posts/Linux', '/posts/Linux', Record<never, never>, Record<never, never>>,
    '/posts/Quantum-Mechanics': RouteRecordInfo<'/posts/Quantum-Mechanics', '/posts/Quantum-Mechanics', Record<never, never>, Record<never, never>>,
    '/posts/Reference-Translation1--PycWB': RouteRecordInfo<'/posts/Reference-Translation1--PycWB', '/posts/Reference-Translation1--PycWB', Record<never, never>, Record<never, never>>,
    '/posts/Theory-of-Relativity-Chapter-2': RouteRecordInfo<'/posts/Theory-of-Relativity-Chapter-2', '/posts/Theory-of-Relativity-Chapter-2', Record<never, never>, Record<never, never>>,
    '/posts/try': RouteRecordInfo<'/posts/try', '/posts/try', Record<never, never>, Record<never, never>>,
    '/posts/VScode and GFortran': RouteRecordInfo<'/posts/VScode and GFortran', '/posts/VScode and GFortran', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
